blueprint:
  name: |-
    ehmtxv2: hide screen elements to 8x32 RGB-display
  description: removes the gauge,indicator or alarm element from your display
  domain: automation
  input:
    ehmtx_device:
      name: which device to display at
      selector:
        device:
          integration: esphome
    trigger_sensor:
      name: which statechange triggers
      description: this entity triggers
      selector:
        entity:
          domain: sensor
    element:
      name: the element
      selector:
        select:
          custom_value: true
          mode: dropdown
          options:
           - label: alarm
             value: hide_alarm
           - label: gauge
             value: hide_gauge
           - label: indicator
             value: hide_indicator
      default: hide_indicator
    
variables:
  display: !input ehmtx_device
  service: !input element

trigger:
  - platform: state
    entity_id: !input trigger_sensor

action:
  - service: esphome.{{ device_attr(display, "name") }}_{{service}}
