blueprint:
  name: |-
    ehmtxv2: delete screen from 8x32 RGB-display
  description: This blueprint is triggered by a state change. If the state is between certain values it will be displayed with special colors or no state change will be displayed
  domain: automation
  input:
    ehmtx_device:
      name: which device to display at
      selector:
        device:
          integration: esphome
    trigger_sensor:
      name: which state change triggers
      description: this entity triggers
      selector:
        entity:
          domain: sensor
    screen_mode:
      name: the mode
      selector:
        select:
          custom_value: true
          mode: dropdown
          options:
            - label: MODE_ICONSCREEN
              value: "5"
            - label: MODE_BLANK
              value: "1"
            - label: MODE_CLOCK
              value: "2" 
            - label: MODE_DATE 
              value: "3"
            - label: MODE_FULLSCREEN
              value: "4"
            - label: MODE_TEXT 
              value: "6"
            - label: MODE_RAINBOW_ICON 
              value: "7"
            - label: MODE_RAINBOW_TEXT 
              value: "8"
      default: "5"
    icon_name:
      name: the icon
      selector:
        select:
          mode: dropdown
          options:
            ["*","error","home_assistant","temperature","lightbulb","music","phone","car","sleep8x32",]
      default: home_assistant
    low_value:
      name: below this vaule is a special color
      selector:
        number:
          mode: box
          min: -10000
          max: +10000
    low_color:
      name: Low color
      description: the color for values below the limit
      selector:
        color_rgb:
      default: [40, 240, 40]

variables:
  display: !input ehmtx_device

trigger:
  - platform: state
    entity_id: !input trigger_sensor

action:
  sequence:
    - service: esphome.{{ device_attr(display, "name") }}_del_screen
      data:
        icon_name: !input icon_name
        mode: !input screen_mode 
  